<?php
/**
 * DomainVerification
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  GoodSender
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace GoodSender\Model;

use \ArrayAccess;
use \GoodSender\ObjectSerializer;

/**
 * DomainVerification Class Doc Comment
 *
 * @category Class
 * @description Per-record verification state for the domain. &#x60;verified&#x60; is the overall flag; the individual &#x60;*_verified&#x60; fields indicate which DNS records still need attention when &#x60;verified&#x60; is &#x60;false&#x60;.
 * @package  GoodSender
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DomainVerification implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'DomainVerification';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'verified' => 'bool',
        'tracking_verified' => 'bool',
        'return_path_verified' => 'bool',
        'dkim1_verified' => 'bool',
        'dkim2_verified' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'verified' => null,
        'tracking_verified' => null,
        'return_path_verified' => null,
        'dkim1_verified' => null,
        'dkim2_verified' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'verified' => false,
        'tracking_verified' => false,
        'return_path_verified' => false,
        'dkim1_verified' => false,
        'dkim2_verified' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'verified' => 'verified',
        'tracking_verified' => 'tracking_verified',
        'return_path_verified' => 'return_path_verified',
        'dkim1_verified' => 'dkim1_verified',
        'dkim2_verified' => 'dkim2_verified'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'verified' => 'setVerified',
        'tracking_verified' => 'setTrackingVerified',
        'return_path_verified' => 'setReturnPathVerified',
        'dkim1_verified' => 'setDkim1Verified',
        'dkim2_verified' => 'setDkim2Verified'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'verified' => 'getVerified',
        'tracking_verified' => 'getTrackingVerified',
        'return_path_verified' => 'getReturnPathVerified',
        'dkim1_verified' => 'getDkim1Verified',
        'dkim2_verified' => 'getDkim2Verified'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('verified', $data ?? [], null);
        $this->setIfExists('tracking_verified', $data ?? [], null);
        $this->setIfExists('return_path_verified', $data ?? [], null);
        $this->setIfExists('dkim1_verified', $data ?? [], null);
        $this->setIfExists('dkim2_verified', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['verified'] === null) {
            $invalidProperties[] = "'verified' can't be null";
        }
        if ($this->container['tracking_verified'] === null) {
            $invalidProperties[] = "'tracking_verified' can't be null";
        }
        if ($this->container['return_path_verified'] === null) {
            $invalidProperties[] = "'return_path_verified' can't be null";
        }
        if ($this->container['dkim1_verified'] === null) {
            $invalidProperties[] = "'dkim1_verified' can't be null";
        }
        if ($this->container['dkim2_verified'] === null) {
            $invalidProperties[] = "'dkim2_verified' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets verified
     *
     * @return bool
     */
    public function getVerified()
    {
        return $this->container['verified'];
    }

    /**
     * Sets verified
     *
     * @param bool $verified Overall verification status. True only when every required DNS record is in place.
     *
     * @return self
     */
    public function setVerified($verified)
    {
        if (is_null($verified)) {
            throw new \InvalidArgumentException('non-nullable verified cannot be null');
        }
        $this->container['verified'] = $verified;

        return $this;
    }

    /**
     * Gets tracking_verified
     *
     * @return bool
     */
    public function getTrackingVerified()
    {
        return $this->container['tracking_verified'];
    }

    /**
     * Sets tracking_verified
     *
     * @param bool $tracking_verified Whether the tracking subdomain CNAME is in place.
     *
     * @return self
     */
    public function setTrackingVerified($tracking_verified)
    {
        if (is_null($tracking_verified)) {
            throw new \InvalidArgumentException('non-nullable tracking_verified cannot be null');
        }
        $this->container['tracking_verified'] = $tracking_verified;

        return $this;
    }

    /**
     * Gets return_path_verified
     *
     * @return bool
     */
    public function getReturnPathVerified()
    {
        return $this->container['return_path_verified'];
    }

    /**
     * Sets return_path_verified
     *
     * @param bool $return_path_verified Whether the return-path subdomain CNAME is in place.
     *
     * @return self
     */
    public function setReturnPathVerified($return_path_verified)
    {
        if (is_null($return_path_verified)) {
            throw new \InvalidArgumentException('non-nullable return_path_verified cannot be null');
        }
        $this->container['return_path_verified'] = $return_path_verified;

        return $this;
    }

    /**
     * Gets dkim1_verified
     *
     * @return bool
     */
    public function getDkim1Verified()
    {
        return $this->container['dkim1_verified'];
    }

    /**
     * Sets dkim1_verified
     *
     * @param bool $dkim1_verified Whether the first DKIM record is in place.
     *
     * @return self
     */
    public function setDkim1Verified($dkim1_verified)
    {
        if (is_null($dkim1_verified)) {
            throw new \InvalidArgumentException('non-nullable dkim1_verified cannot be null');
        }
        $this->container['dkim1_verified'] = $dkim1_verified;

        return $this;
    }

    /**
     * Gets dkim2_verified
     *
     * @return bool
     */
    public function getDkim2Verified()
    {
        return $this->container['dkim2_verified'];
    }

    /**
     * Sets dkim2_verified
     *
     * @param bool $dkim2_verified Whether the second DKIM record is in place.
     *
     * @return self
     */
    public function setDkim2Verified($dkim2_verified)
    {
        if (is_null($dkim2_verified)) {
            throw new \InvalidArgumentException('non-nullable dkim2_verified cannot be null');
        }
        $this->container['dkim2_verified'] = $dkim2_verified;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


