<?php
/**
 * SendEmail
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  GoodSender
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace GoodSender\Model;

use \ArrayAccess;
use \GoodSender\ObjectSerializer;

/**
 * SendEmail Class Doc Comment
 *
 * @category Class
 * @description Must provide valid sender and subject. At least one recipient (from &#39;to&#39;, &#39;cc&#39;, or &#39;bcc&#39;) is required. Either &#39;text_content&#39;, &#39;html_content&#39;, &#39;markdown_content&#39;, or &#39;template_id&#39; is required. When &#39;markdown_content&#39; is provided, &#39;text_content&#39; and &#39;html_content&#39; are ignored.
 * @package  GoodSender
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SendEmail implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'SendEmail';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'from' => '\GoodSender\Model\Address',
        'to' => '\GoodSender\Model\Address[]',
        'subject' => 'string',
        'text_content' => 'string',
        'html_content' => 'string',
        'markdown_content' => 'string',
        'template_id' => 'string',
        'template_data' => 'array<string,mixed>',
        'attachments' => '\GoodSender\Model\Attachment[]',
        'headers' => 'array<string,string>',
        'reply_to' => '\GoodSender\Model\Address',
        'send_time' => 'int',
        'webhook_data' => 'array<string,string>',
        'tag' => 'string',
        'tracking' => '\GoodSender\Model\TrackingSettings'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'from' => null,
        'to' => null,
        'subject' => null,
        'text_content' => null,
        'html_content' => null,
        'markdown_content' => null,
        'template_id' => null,
        'template_data' => null,
        'attachments' => null,
        'headers' => null,
        'reply_to' => null,
        'send_time' => 'int64',
        'webhook_data' => null,
        'tag' => null,
        'tracking' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'from' => false,
        'to' => false,
        'subject' => false,
        'text_content' => false,
        'html_content' => false,
        'markdown_content' => false,
        'template_id' => false,
        'template_data' => false,
        'attachments' => false,
        'headers' => false,
        'reply_to' => false,
        'send_time' => false,
        'webhook_data' => false,
        'tag' => false,
        'tracking' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'from' => 'from',
        'to' => 'to',
        'subject' => 'subject',
        'text_content' => 'text_content',
        'html_content' => 'html_content',
        'markdown_content' => 'markdown_content',
        'template_id' => 'template_id',
        'template_data' => 'template_data',
        'attachments' => 'attachments',
        'headers' => 'headers',
        'reply_to' => 'reply_to',
        'send_time' => 'send_time',
        'webhook_data' => 'webhook_data',
        'tag' => 'tag',
        'tracking' => 'tracking'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'from' => 'setFrom',
        'to' => 'setTo',
        'subject' => 'setSubject',
        'text_content' => 'setTextContent',
        'html_content' => 'setHtmlContent',
        'markdown_content' => 'setMarkdownContent',
        'template_id' => 'setTemplateId',
        'template_data' => 'setTemplateData',
        'attachments' => 'setAttachments',
        'headers' => 'setHeaders',
        'reply_to' => 'setReplyTo',
        'send_time' => 'setSendTime',
        'webhook_data' => 'setWebhookData',
        'tag' => 'setTag',
        'tracking' => 'setTracking'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'from' => 'getFrom',
        'to' => 'getTo',
        'subject' => 'getSubject',
        'text_content' => 'getTextContent',
        'html_content' => 'getHtmlContent',
        'markdown_content' => 'getMarkdownContent',
        'template_id' => 'getTemplateId',
        'template_data' => 'getTemplateData',
        'attachments' => 'getAttachments',
        'headers' => 'getHeaders',
        'reply_to' => 'getReplyTo',
        'send_time' => 'getSendTime',
        'webhook_data' => 'getWebhookData',
        'tag' => 'getTag',
        'tracking' => 'getTracking'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('from', $data ?? [], null);
        $this->setIfExists('to', $data ?? [], null);
        $this->setIfExists('subject', $data ?? [], '');
        $this->setIfExists('text_content', $data ?? [], null);
        $this->setIfExists('html_content', $data ?? [], null);
        $this->setIfExists('markdown_content', $data ?? [], null);
        $this->setIfExists('template_id', $data ?? [], null);
        $this->setIfExists('template_data', $data ?? [], null);
        $this->setIfExists('attachments', $data ?? [], null);
        $this->setIfExists('headers', $data ?? [], null);
        $this->setIfExists('reply_to', $data ?? [], null);
        $this->setIfExists('send_time', $data ?? [], null);
        $this->setIfExists('webhook_data', $data ?? [], null);
        $this->setIfExists('tag', $data ?? [], null);
        $this->setIfExists('tracking', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['from'] === null) {
            $invalidProperties[] = "'from' can't be null";
        }
        if ($this->container['to'] === null) {
            $invalidProperties[] = "'to' can't be null";
        }
        if ($this->container['subject'] === null) {
            $invalidProperties[] = "'subject' can't be null";
        }
        if (!is_null($this->container['markdown_content']) && (mb_strlen($this->container['markdown_content']) < 1)) {
            $invalidProperties[] = "invalid value for 'markdown_content', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets from
     *
     * @return \GoodSender\Model\Address
     */
    public function getFrom()
    {
        return $this->container['from'];
    }

    /**
     * Sets from
     *
     * @param \GoodSender\Model\Address $from Sender address (required)
     *
     * @return self
     */
    public function setFrom($from)
    {
        if (is_null($from)) {
            throw new \InvalidArgumentException('non-nullable from cannot be null');
        }
        $this->container['from'] = $from;

        return $this;
    }

    /**
     * Gets to
     *
     * @return \GoodSender\Model\Address[]
     */
    public function getTo()
    {
        return $this->container['to'];
    }

    /**
     * Sets to
     *
     * @param \GoodSender\Model\Address[] $to To recipients. At least one recipient (to, cc, or bcc) is required. Maximum 1000 recipients per email.
     *
     * @return self
     */
    public function setTo($to)
    {
        if (is_null($to)) {
            throw new \InvalidArgumentException('non-nullable to cannot be null');
        }
        $this->container['to'] = $to;

        return $this;
    }

    /**
     * Gets subject
     *
     * @return string
     */
    public function getSubject()
    {
        return $this->container['subject'];
    }

    /**
     * Sets subject
     *
     * @param string $subject The subject of the email (required)
     *
     * @return self
     */
    public function setSubject($subject)
    {
        if (is_null($subject)) {
            throw new \InvalidArgumentException('non-nullable subject cannot be null');
        }
        $this->container['subject'] = $subject;

        return $this;
    }

    /**
     * Gets text_content
     *
     * @return string|null
     */
    public function getTextContent()
    {
        return $this->container['text_content'];
    }

    /**
     * Sets text_content
     *
     * @param string|null $text_content Plain text content
     *
     * @return self
     */
    public function setTextContent($text_content)
    {
        if (is_null($text_content)) {
            throw new \InvalidArgumentException('non-nullable text_content cannot be null');
        }
        $this->container['text_content'] = $text_content;

        return $this;
    }

    /**
     * Gets html_content
     *
     * @return string|null
     */
    public function getHtmlContent()
    {
        return $this->container['html_content'];
    }

    /**
     * Sets html_content
     *
     * @param string|null $html_content HTML content
     *
     * @return self
     */
    public function setHtmlContent($html_content)
    {
        if (is_null($html_content)) {
            throw new \InvalidArgumentException('non-nullable html_content cannot be null');
        }
        $this->container['html_content'] = $html_content;

        return $this;
    }

    /**
     * Gets markdown_content
     *
     * @return string|null
     */
    public function getMarkdownContent()
    {
        return $this->container['markdown_content'];
    }

    /**
     * Sets markdown_content
     *
     * @param string|null $markdown_content Markdown content. When provided, text_content and html_content are ignored. The raw markdown is used as text_content and rendered to HTML for html_content.
     *
     * @return self
     */
    public function setMarkdownContent($markdown_content)
    {
        if (is_null($markdown_content)) {
            throw new \InvalidArgumentException('non-nullable markdown_content cannot be null');
        }

        if ((mb_strlen($markdown_content) < 1)) {
            throw new \InvalidArgumentException('invalid length for $markdown_content when calling SendEmail., must be bigger than or equal to 1.');
        }

        $this->container['markdown_content'] = $markdown_content;

        return $this;
    }

    /**
     * Gets template_id
     *
     * @return string|null
     */
    public function getTemplateId()
    {
        return $this->container['template_id'];
    }

    /**
     * Sets template_id
     *
     * @param string|null $template_id Template ID for templated emails
     *
     * @return self
     */
    public function setTemplateId($template_id)
    {
        if (is_null($template_id)) {
            throw new \InvalidArgumentException('non-nullable template_id cannot be null');
        }
        $this->container['template_id'] = $template_id;

        return $this;
    }

    /**
     * Gets template_data
     *
     * @return array<string,mixed>|null
     */
    public function getTemplateData()
    {
        return $this->container['template_data'];
    }

    /**
     * Sets template_data
     *
     * @param array<string,mixed>|null $template_data Data to populate template variables
     *
     * @return self
     */
    public function setTemplateData($template_data)
    {
        if (is_null($template_data)) {
            throw new \InvalidArgumentException('non-nullable template_data cannot be null');
        }
        $this->container['template_data'] = $template_data;

        return $this;
    }

    /**
     * Gets attachments
     *
     * @return \GoodSender\Model\Attachment[]|null
     */
    public function getAttachments()
    {
        return $this->container['attachments'];
    }

    /**
     * Sets attachments
     *
     * @param \GoodSender\Model\Attachment[]|null $attachments Email attachments
     *
     * @return self
     */
    public function setAttachments($attachments)
    {
        if (is_null($attachments)) {
            throw new \InvalidArgumentException('non-nullable attachments cannot be null');
        }
        $this->container['attachments'] = $attachments;

        return $this;
    }

    /**
     * Gets headers
     *
     * @return array<string,string>|null
     */
    public function getHeaders()
    {
        return $this->container['headers'];
    }

    /**
     * Sets headers
     *
     * @param array<string,string>|null $headers Custom email headers
     *
     * @return self
     */
    public function setHeaders($headers)
    {
        if (is_null($headers)) {
            throw new \InvalidArgumentException('non-nullable headers cannot be null');
        }
        $this->container['headers'] = $headers;

        return $this;
    }

    /**
     * Gets reply_to
     *
     * @return \GoodSender\Model\Address|null
     */
    public function getReplyTo()
    {
        return $this->container['reply_to'];
    }

    /**
     * Sets reply_to
     *
     * @param \GoodSender\Model\Address|null $reply_to Reply-to address
     *
     * @return self
     */
    public function setReplyTo($reply_to)
    {
        if (is_null($reply_to)) {
            throw new \InvalidArgumentException('non-nullable reply_to cannot be null');
        }
        $this->container['reply_to'] = $reply_to;

        return $this;
    }

    /**
     * Gets send_time
     *
     * @return int|null
     */
    public function getSendTime()
    {
        return $this->container['send_time'];
    }

    /**
     * Sets send_time
     *
     * @param int|null $send_time Unix timestamp for when to send the email. Must not be more than 72 hours in the future. If 0, sends immediately.
     *
     * @return self
     */
    public function setSendTime($send_time)
    {
        if (is_null($send_time)) {
            throw new \InvalidArgumentException('non-nullable send_time cannot be null');
        }
        $this->container['send_time'] = $send_time;

        return $this;
    }

    /**
     * Gets webhook_data
     *
     * @return array<string,string>|null
     */
    public function getWebhookData()
    {
        return $this->container['webhook_data'];
    }

    /**
     * Sets webhook_data
     *
     * @param array<string,string>|null $webhook_data Custom data to include in webhook events. Maximum 10 keys, key length 50 chars, value length 100 chars.
     *
     * @return self
     */
    public function setWebhookData($webhook_data)
    {
        if (is_null($webhook_data)) {
            throw new \InvalidArgumentException('non-nullable webhook_data cannot be null');
        }
        $this->container['webhook_data'] = $webhook_data;

        return $this;
    }

    /**
     * Gets tag
     *
     * @return string|null
     */
    public function getTag()
    {
        return $this->container['tag'];
    }

    /**
     * Sets tag
     *
     * @param string|null $tag Custom tag for tracking. Maximum 100 characters.
     *
     * @return self
     */
    public function setTag($tag)
    {
        if (is_null($tag)) {
            throw new \InvalidArgumentException('non-nullable tag cannot be null');
        }
        $this->container['tag'] = $tag;

        return $this;
    }

    /**
     * Gets tracking
     *
     * @return \GoodSender\Model\TrackingSettings|null
     */
    public function getTracking()
    {
        return $this->container['tracking'];
    }

    /**
     * Sets tracking
     *
     * @param \GoodSender\Model\TrackingSettings|null $tracking Email tracking settings
     *
     * @return self
     */
    public function setTracking($tracking)
    {
        if (is_null($tracking)) {
            throw new \InvalidArgumentException('non-nullable tracking cannot be null');
        }
        $this->container['tracking'] = $tracking;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


