<?php
/**
 * DomainVerificationTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  GoodSender
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace GoodSender\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DomainVerificationTest Class Doc Comment
 *
 * @category    Class
 * @description Per-record verification state for the domain. &#x60;verified&#x60; is the overall flag; the individual &#x60;*_verified&#x60; fields indicate which DNS records still need attention when &#x60;verified&#x60; is &#x60;false&#x60;.
 * @package     GoodSender
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DomainVerificationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DomainVerification"
     */
    public function testDomainVerification()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "verified"
     */
    public function testPropertyVerified()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tracking_verified"
     */
    public function testPropertyTrackingVerified()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "return_path_verified"
     */
    public function testPropertyReturnPathVerified()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dkim1_verified"
     */
    public function testPropertyDkim1Verified()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dkim2_verified"
     */
    public function testPropertyDkim2Verified()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
