<?php
/**
 * EmailListResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  GoodSender
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace GoodSender\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * EmailListResponseTest Class Doc Comment
 *
 * @category    Class
 * @description EmailListResponse
 * @package     GoodSender
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EmailListResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "EmailListResponse"
     */
    public function testEmailListResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "emails"
     */
    public function testPropertyEmails()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "next_cursor"
     */
    public function testPropertyNextCursor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
