<?php
/**
 * EmailsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  GoodSender
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace GoodSender\Test\Api;

use \GoodSender\Configuration;
use \GoodSender\ApiException;
use \GoodSender\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * EmailsApiTest Class Doc Comment
 *
 * @category Class
 * @package  GoodSender
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EmailsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getEmailConsentStatus
     *
     * Get recipient consent status.
     *
     */
    public function testGetEmailConsentStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listEmailConsents
     *
     * List email consent statuses.
     *
     */
    public function testListEmailConsents()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for requestEmailConsent
     *
     * Request recipients' consent to receive emails from your domain.
     *
     */
    public function testRequestEmailConsent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendEmail
     *
     * Send an email or a batch of emails.
     *
     */
    public function testSendEmail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendTemplateEmail
     *
     * Send a transactional email using a template.
     *
     */
    public function testSendTemplateEmail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
